
CREATE ROLE pro_user1 WITH LOGIN PASSWORD '123456';
CREATE ROLE pro_user2 WITH LOGIN PASSWORD '123456';

CREATE ROLE sale_user1 WITH LOGIN PASSWORD '123456';
CREATE ROLE sale_user2 WITH LOGIN PASSWORD '123456';

GRANT USAGE ON SCHEMA production TO pro_user1;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA production TO pro_user1;

GRANT USAGE ON SCHEMA production TO pro_user2;

GRANT USAGE ON SCHEMA sales TO sale_user1;
GRANT USAGE ON SCHEMA sales TO sale_user2;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sales TO sale_user2;

SELECT current_user; 

select * from sales.orders
